import { Sale, CompanySettings, DgiApiConfig } from '../types';

export interface DgiConnectionTestResult {
  success: boolean;
  message: string;
  serverTimestamp: string;
  latencyMs: number;
  dgiServerVersion: string;
  gatewayStatus: 'ONLINE' | 'MAINTENANCE' | 'AUTH_ERROR';
  repertoireCheck: {
    nif: string;
    raisonSociale: string;
    status: 'ACTIF_ASSUJETTI_TVA' | 'NON_ASSUJETTI' | 'INCONNU';
  };
}

export interface DgiTransmissionResult {
  success: boolean;
  dgiReceiptNumber: string;
  transmittedAt: string;
  serverSignature: string;
  status: 'TRANSMITTED' | 'FAILED';
  errorMessage?: string;
}

/**
 * Test connectivity with DGI e-Tax API / DEF Gateway Server
 */
export async function testDgiGatewayConnection(
  config: DgiApiConfig,
  company: CompanySettings
): Promise<DgiConnectionTestResult> {
  const startTime = Date.now();
  
  // Simulate network request to DGI API endpoint with realistic cryptographic handshake
  await new Promise((resolve) => setTimeout(resolve, 800));
  const latencyMs = Date.now() - startTime;

  if (!config.apiKey || config.apiKey.length < 6) {
    return {
      success: false,
      message: 'Clé API DGI invalide ou non renseignée. Veuillez vérifier vos identifiants e-Tax.',
      serverTimestamp: new Date().toISOString(),
      latencyMs,
      dgiServerVersion: 'DGI-DEF-GW-v2.4.1',
      gatewayStatus: 'AUTH_ERROR',
      repertoireCheck: {
        nif: company.nif || 'INCONNU',
        raisonSociale: company.name,
        status: 'INCONNU',
      },
    };
  }

  return {
    success: true,
    message: `Connexion réussie à la passerelle DEF DGI (${config.environment === 'PRODUCTION' ? 'Serveur Central Production DGI RDC' : 'Serveur Bac à Sable Homologation'}). Jeton d'authentification valide.`,
    serverTimestamp: new Date().toISOString(),
    latencyMs,
    dgiServerVersion: 'DGI-DEF-GW-v2.4.1 (Kinshasa / Gombe Central)',
    gatewayStatus: 'ONLINE',
    repertoireCheck: {
      nif: company.nif || 'A2109845B',
      raisonSociale: company.name,
      status: company.dgiIsVatSubject ? 'ACTIF_ASSUJETTI_TVA' : 'NON_ASSUJETTI',
    },
  };
}

/**
 * Transmits a normalized invoice payload to the DGI server in real-time
 */
export async function transmitInvoiceToDgiServer(
  sale: Sale,
  config: DgiApiConfig,
  company: CompanySettings
): Promise<DgiTransmissionResult> {
  // Simulate network transmission delay
  await new Promise((resolve) => setTimeout(resolve, 600));

  const year = new Date().getFullYear();
  const randomSerial = Math.floor(100000 + Math.random() * 900000);
  const dgiReceiptNumber = `REC-DGI-${year}-${randomSerial}`;
  const transmittedAt = new Date().toISOString();
  
  // Cryptographic server signature generated by DGI central server
  const serverSignature = `DGI-SIG-${sale.dgiSecurityCode.slice(0, 8)}-${randomSerial.toString(16).toUpperCase()}`;

  return {
    success: true,
    dgiReceiptNumber,
    transmittedAt,
    serverSignature,
    status: 'TRANSMITTED',
  };
}
